#!/bin/bash

if [ -n "$1" ] && [ ! -d "$1" ]; then
  echo >&2 "$1 is not a directory"
  exit 1
fi

WD="${1:-$(dirname "$(readlink -f "$0")")}"

echo "/* This file was auto-generated by $(basename "$0") */"
echo '
#include "greatest.h"
'

find "$WD" -type f -name '*.c' -exec cat {} \; | grep -oe '^SUITE *([^)]*)' |
    sed -e 's/^SUITE */SUITE_EXTERN/' \
        -e 's/$/;/'

echo '
GREATEST_MAIN_DEFS();

int main(int argc, char **argv) {
    GREATEST_MAIN_BEGIN();'

find "$WD" -type f -name '*.c' -exec cat {} \; | grep -oe '^SUITE *([^)]*)' |
    sed -e 's/^SUITE */    RUN_SUITE/' \
        -e 's/$/;/'

echo '    GREATEST_MAIN_END();'
echo '}'
